'use strict';
const ROOMS=[
{name:'Articulatory description',short:'Articulation',symbol:'[ ]',intro:'Identify the properties of consonants and vowels.',debrief:'Does changing one articulatory property always produce a different word?'},
{name:'Evidence for contrast',short:'Contrast',symbol:'/ /',intro:'Evaluate minimal pairs and the conclusions they support.',debrief:'What does a minimal pair establish? What does failing to find one leave unresolved?'},
{name:'Allophonic distribution',short:'Distribution',symbol:'ʰ',intro:'Describe distributions and apply rules to new data.',debrief:'Why did we distinguish word-final position from syllable-final position within a word?'},
{name:'Velar and palatal stops',short:'Analysis',symbol:'c',intro:'Combine distributional evidence with evidence for contrast.',debrief:'How can predictable variation in one environment coexist with contrast in another?'}];
const CASES=[
{title:'Describe [d]',data:'[d] — the first sound in dilbilim',q:'Complete the articulatory description.',type:'fields',fields:[['Voicing',['Voiced','Voiceless'],0],['Place of articulation',['Dental','Bilabial','Velar'],0],['Manner of articulation',['Fricative','Stop','Nasal'],1]],reasons:['The vocal folds vibrate, with complete oral closure at the dental place of articulation.','The lips close and air passes through the nose.','Air passes continuously through a narrow oral constriction.'],r:0,hint:'Separate the three questions: vocal-fold activity, location of constriction, and degree of constriction.',explain:'In the handout, [d] is a voiced dental oral stop. The three selected properties describe voicing, place, and manner; oral is also part of its full description.',source:'W1 handout-b · pp. 4–5, 7',talk:'Produce [t] instead. Which property changes?'},
{title:'Compare two vowels',data:'kıl: ı     /     kil: i',q:'Select ALL dimensions on which the two vowels differ.',type:'multi',options:['Height','Backness','Rounding'],answer:[1],reasons:['Both are high and unrounded; ı is back and i is front.','ı is low and i is high; both are front.','ı is rounded and i is unrounded; both are back.'],r:0,hint:'Check height, backness, and rounding separately.',explain:'In the W1 chart, both vowels are high and unrounded. They differ in backness. Here ı is the Turkish orthographic letter; its IPA counterpart is [ɯ].',source:'W1 handout-b · pp. 6–7',talk:'Which dimension distinguishes ü from i?'},
{title:'Oral and nasal airflow',data:'[m]     ↔     [b]',q:'Which movement opens the nasal passage for [m]?',type:'choice',options:['Lowering the velum','Raising the velum','Stopping vocal-fold vibration','Opening the lips completely'],answer:0,reasons:['A lowered velum allows airflow through the nasal cavity.','All voiced sounds are nasal.','Bilabial sounds permit airflow only through the mouth.'],r:0,hint:'Both sounds involve lip closure and vocal-fold vibration. Consider the velum.',explain:'The velum is lowered for [m], allowing nasal airflow, and raised for [b]. Both sounds are voiced and bilabial. [m] is nasal; [b] is an oral stop.',source:'W1 handout-b · pp. 3–5',talk:'What happens if you gently close your nose while producing [m]?'},
{title:'Broad and narrow transcription',data:'kuş     [kuʃ]     [kʰuʃ]',q:'How do the two transcriptions differ?',type:'choice',options:['The first is broader; the second includes more phonetic detail.','They represent two words with different meanings.','ʰ marks vowel length.','Square brackets indicate ordinary spelling.'],answer:0,reasons:['A narrower transcription can represent aspiration explicitly.','IPA merely replaces the letters of an alphabet.','Adding a symbol necessarily adds a phoneme.'],r:0,hint:'Broad and narrow refer to the amount of phonetic detail represented.',explain:'[kuʃ] is broader; [kʰuʃ] explicitly marks aspiration. The superscript ʰ is a diacritic for aspiration, not an additional segment.',source:'W1 handout-a · p. 3',talk:'How does this example qualify the claim that Turkish is pronounced exactly as it is written?'},
{title:'Choose a minimal pair',data:'Hypothesis: [p] and [b] represent distinct phonemes in Turkish.',q:'Which minimal pair supports the hypothesis?',type:'choice',options:['kapak – kabak','kapak – tabak','pil – bal','para – burun'],answer:0,reasons:['Only one sound differs, in the same position, and the meanings differ.','Having the same number of syllables is sufficient.','Any difference in spelling establishes a minimal pair.'],r:0,hint:'Align the segments and count the differences.',explain:'kapak “lid” and kabak “zucchini” differ only in [p] versus [b] in the same environment. This supports a /p/–/b/ contrast. The other pairs differ in more than one segment.',source:'W2 presentation-a · p. 1',talk:'Which articulatory property distinguishes [p] and [b] here?'},
{title:'Identify the contrastive property',data:'kas “muscle”     /     kaz “goose”\nsil “erase”      /     zil “bell”',q:'Which property do both pairs test?',type:'choice',options:['Voicing','Aspiration','Vowel height','Nasality'],answer:0,reasons:['[s] and [z] share place and manner but differ in voicing.','Each pair compares a stop and a fricative.','The meanings remain the same, so the difference is only phonetic.'],r:0,hint:'Produce [ssss] and [zzzz] while gently touching your larynx.',explain:'[s] is voiceless and [z] is voiced. These minimal pairs show that this distinction can differentiate meanings in Turkish. A contrastive property need not distinguish every possible pair of sounds.',source:'W1 handout-b · p. 3',talk:'How would af–av test the same hypothesis?'},
{title:'Evaluate an inference',data:'Data: [kʰ]ar and [k]ar refer to the same word, kar “snow”.\nClaim: “An audible difference always means two phonemes.”',q:'Which objection is best supported?',type:'choice',options:['A phonetic difference alone does not establish phonemic contrast.','Sounds written with the same letter must always be the same phoneme.','Aspiration cannot distinguish meaning in any language.','If meaning is unchanged, the sounds are phonetically identical.'],answer:0,reasons:['We must also examine the function and distribution of the difference in the language.','The alphabet determines the phonemic analysis on its own.','A property must have the same function in every language.'],r:0,hint:'The handout compares aspiration in Turkish and Eastern Armenian.',explain:'Aspiration is a real phonetic difference. In this Turkish example it does not create a meaning contrast. The handout’s Eastern Armenian comparison illustrates that the same property can be contrastive in another language.',source:'W1 handout-b · p. 3; W2 presentation-a · p. 1',talk:'What distributional questions would you ask before proposing an allophonic analysis?'},
{title:'Recognize insufficient evidence',data:'A researcher has not yet found a minimal pair for two sounds,\nlabelled X and Y. No other evidence is available.',q:'Which conclusion is justified at this stage?',type:'choice',options:['More evidence is needed about their distributions and potential contrasts.','They must be allophones of the same phoneme.','They must be separate phonemes.','The sounds cannot occur in the language.'],answer:0,reasons:['Not having found evidence for contrast does not demonstrate the absence of contrast.','Failure to find a minimal pair always establishes free variation.','Phonemes can be investigated only in word-initial position.'],r:0,hint:'Distinguish “not found yet” from “does not exist”.',explain:'This applies the handout’s observation–hypothesis–test approach to a new situation. With the stated evidence alone, neither phonemic contrast nor allophony has been established.',source:'W1 handout-b · p. 3; W2 presentation-a · pp. 1–2',talk:'Which word positions and sound environments would you investigate next?'},
{title:'Classify /p/ realizations',data:'Target /p/: pat · kapak · kapla · top',q:'Assign each realization using the W2 aspiration model.',type:'fields',fields:[['pat · initial /p/',['[pʰ]','[p]'],0],['kapak · medial /p/',['[pʰ]','[p]'],0],['kapla · /p/',['[pʰ]','[p]'],1],['top · final /p/',['[pʰ]','[p]'],0]],reasons:['[p] occurs syllable-finally within a word; [pʰ] occurs in the other listed positions.','[p] occurs in all syllable-final positions, including word-finally.','Only the rounding of an adjacent vowel determines aspiration.'],r:0,hint:'Distinguish kap.la from top. W2 lists word-final position separately.',explain:'In the course model, pat is word-initial, ka.pak is syllable-initial, kap.la is syllable-final within a word, and top is word-final. The expected sequence is [pʰ], [pʰ], [p], [pʰ]. This applies the slides’ model, not a universal claim about every speaking context.',source:'W2 presentation-a · p. 2',talk:'Why is “no aspiration syllable-finally” an incomplete summary of these data?'},
{title:'Choose a distributional rule',data:'[tʰ]aş · a[tʰ]a · a[tʰ]\na[t]la',q:'Which rule best summarizes this dataset?',type:'choice',options:['/t/ → [t] / __ $ within a word; [tʰ] in the other given positions','/t/ → [tʰ] / __ $ within a word; [t] in the other given positions','/t/ → [t] only word-initially','/t/ → [tʰ] only after back vowels'],answer:0,reasons:['The /t/ in at.la is syllable-final within the word; the other examples occupy different positions.','The /t/ in at and atla occurs in exactly the same environment.','taş and ata cannot fall under the same rule because their first letters differ.'],r:0,hint:'$ marks a syllable boundary; __ marks the position of the target segment.',explain:'W2 treats [t] in word-internal syllable-final position and [tʰ] in the other given positions as realizations of /t/. The distribution supports an allophonic analysis in the course model.',source:'W2 presentation-a · pp. 1, 3',talk:'Is extending this rule to /p/ a new hypothesis or an observation?'},
{title:'Predict a new example',data:'Prediction task: etki\nSyllabification is supplied: et.ki',q:'What does the W2 distribution predict for this /t/?',type:'choice',options:['Unaspirated [t]','Aspirated [tʰ]','Voiced [d]','Deletion of the consonant'],answer:0,reasons:['The /t/ is syllable-final inside the word.','Every stop after a front vowel becomes voiced.','All stops in two-syllable words are aspirated.'],r:0,hint:'Apply the stated environment rather than relying on a memorized word.',explain:'In et.ki, /t/ ends the first syllable but is not word-final. Extending the W2 distribution predicts [t]. This is a model-based prediction; no recording is being evaluated here.',source:'W2 presentation-a · p. 3; application of the stated rule',talk:'What recording and comparison would let you test this prediction?'},
{title:'Distinguish phoneme and allophone',data:'Proposed analysis: “Turkish /t/ and /tʰ/ are separate\nphonemes because aspiration distinguishes meaning.”',q:'Which revision matches the course analysis?',type:'choice',options:['The phoneme /t/ has the allophones [t] and [tʰ].','The phoneme [t] has the letters /t/ and /tʰ/.','/t/ and /d/ are allophones of the same phoneme.','Aspiration is a vowel property.'],answer:0,reasons:['Aspiration is predictable in the stated distribution and does not establish a [t]–[tʰ] meaning contrast.','Their shared spelling is sufficient evidence.','Their articulations are identical in every respect.'],r:0,hint:'Use / / for phonemes and [ ] for phonetic realizations.',explain:'W2 analyzes [t] and [tʰ] as allophones of /t/. The phonetic difference is real, but it is not contrastive in these data. Orthography alone does not establish the analysis.',source:'W2 presentation-a · pp. 1–3',talk:'How does tut–dut provide a different kind of evidence for /t/ and /d/?'},
{title:'Compare places of articulation',data:'kalem     /     kel\nTarget: the initial consonant written k',q:'Match each consonant to its place of articulation in W2’s notation.',type:'fields',fields:[['kalem · first sound',['Velar [kʰ]','Palatal [cʰ]'],0],['kel · first sound',['Velar [kʰ]','Palatal [cʰ]'],1]],reasons:['In these regular examples, back versus front vowel context is associated with velar versus palatal realization.','The letter k requires the same place of articulation in every word.','Both consonants are bilabial.'],r:0,hint:'a is back; e is front. IPA [c] is not the sound represented by Turkish orthographic c.',explain:'W2 uses velar [kʰ] for the initial consonant of kalem and palatal [cʰ] for that of kel. IPA [c] is a voiceless palatal stop; it should not be confused with [dʒ], represented by the letter c in Turkish spelling.',source:'W1 handout-b · p. 4; W2 presentation-a · pp. 3–4',talk:'Do voicing and manner remain constant while place changes?'},
{title:'Combine two conditions',data:'W2 model: place of articulation + aspiration\nkol     /     ekmek (ek.mek)\nTarget: the first k in each word',q:'Predict both properties for each target consonant.',type:'fields',fields:[['kol · first k',['[kʰ] velar, aspirated','[k] velar, unaspirated','[cʰ] palatal, aspirated','[c] palatal, unaspirated'],0],['ek.mek · first k',['[kʰ] velar, aspirated','[k] velar, unaspirated','[cʰ] palatal, aspirated','[c] palatal, unaspirated'],3]],reasons:['Vowel context conditions place; the stated syllable and word positions condition aspiration.','A front vowel always requires aspiration.','An unaspirated stop must be velar.'],r:0,hint:'First determine place. Then check whether the consonant is syllable-final within the word.',explain:'For kol, the back vowel context and word-initial position predict [kʰ]. The first /k/ in ek.mek follows a front vowel and is syllable-final within the word: W2 predicts [c]. Two conditions must be tracked separately.',source:'W2 presentation-a · pp. 3–4; application of the stated rules',talk:'What does the W2 model predict for the second k in ekmek? ([cʰ])'},
{title:'Test a generalization',data:'Hypothesis: “Palatal [cʰ] occurs only near front vowels.”\nNew datum: kâr [cʰɑɾ̥]',q:'How does the new datum affect the hypothesis?',type:'choice',options:['It contradicts it: [cʰ] occurs before the back vowel [ɑ].','It confirms it: [ɑ] is a front vowel.','It is irrelevant because only letters should be examined.','It establishes that every Turkish k is palatal.'],answer:0,reasons:['One valid example outside the stated condition can refute an “only” claim.','An exception must automatically be excluded from the dataset.','New data should not be compared with an existing hypothesis.'],r:0,hint:'The regular front-vowel distribution does not account for every occurrence of a palatal stop.',explain:'In kâr, [cʰ] occurs before back [ɑ]. A front-vowel-only account therefore cannot cover all the data. This counterexample does not by itself complete the analysis; the next problem supplies contrastive evidence.',source:'W2 presentation-a · p. 4',talk:'How could you restrict or revise the original hypothesis?'},
{title:'Support a phonemic analysis',data:'kar “snow”     [kʰɑɾ̥]\nkâr “profit”   [cʰɑɾ̥]',q:'Which conclusion is supported by the transcriptions given in W2?',type:'choice',options:['/k/ and /c/ can be analyzed as distinct phonemes in this environment.','Aspiration alone accounts for the meaning difference.','Both initial consonants are velar.','The only difference is vowel length.'],answer:0,reasons:['[kʰ] and [cʰ] occur in the same remaining sound environment and distinguish meanings.','The circumflex alone determines the phoneme inventory without sound evidence.','There is no contrast because [cʰ] occurs only before front vowels.'],r:0,hint:'Compare the two transcriptions segment by segment. Both initial stops are aspirated.',explain:'In the slides’ kar–kâr pair, aspiration and the remaining sound environment are held constant; the initial stop differs in place. W2 uses this as evidence for a /k/–/c/ contrast. Keep this contrastive evidence distinct from predictable palatal realizations near front vowels.',source:'W2 presentation-a · p. 4',talk:'Does predictable variation in one environment prevent contrast in another?'}
];

// Stable choice ordering keeps every team on the same version of each case.
CASES.forEach((c,i)=>{
 const rotate=(items,shift)=>items.map((_,k)=>items[(k+shift)%items.length]);
 if(c.options){const shift=(i*3+1)%c.options.length;c.options=rotate(c.options,shift);c.answer=Array.isArray(c.answer)?c.answer.map(a=>(a-shift+c.options.length)%c.options.length):(c.answer-shift+c.options.length)%c.options.length;}
 const shift=(i+1)%c.reasons.length;c.reasons=rotate(c.reasons,shift);c.r=(c.r-shift+c.reasons.length)%c.reasons.length;
});
const WEEKS=['1–2','3–4','4–5','6–7','8–9','10–11','12'];
const KEY='ling313-phonology-en-v1';
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={weeks:'1–2',screen:'start',mode:'team',team:'',index:0,answers:[],big:false},draft={},storageOK=true;
try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw&&Array.isArray(raw.answers)&&raw.answers.length<=16&&['start','play','break','results'].includes(raw.screen)&&Number.isInteger(raw.index)&&raw.index>=0&&raw.index<16)state={...state,...raw};}catch(e){storageOK=false;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){storageOK=false;}}
function score(){return state.answers.reduce((s,a)=>s+a.points,0);}
function roomScore(i){return state.answers.slice(i*4,i*4+4).reduce((s,a)=>s+a.points,0);}
function resetDraft(){draft={answer:[],fields:[],reason:null,hint:false};}
function render(){document.body.classList.toggle('big-text',state.big);$('displayBtn').setAttribute('aria-pressed',String(state.big));$('displayBtn').textContent=state.big?'Normal text':'Large text';if(state.screen==='start')startScreen();else if(state.screen==='break')breakScreen();else if(state.screen==='results')resultsScreen();else playScreen();}
function focusMain(){window.scrollTo({top:0,behavior:'instant'});const h=$('app').querySelector('h1,h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}
function weekPicker(){return `<section class="week-picker" aria-label="Choose weeks"><h2>Choose weeks</h2><div class="week-options">${WEEKS.map(w=>`<button type="button" data-weeks="${w}" aria-pressed="${state.weeks===w}" class="${state.weeks===w?'selected':''}">${w==='12'?'Week':'Weeks'} ${w}<small>${w==='1–2'?'Available':'To be added'}</small></button>`).join('')}</div></section>`;}
function bindWeekPicker(){document.querySelectorAll('[data-weeks]').forEach(button=>{button.onclick=()=>{if($('teamName'))state.team=$('teamName').value;state.weeks=button.dataset.weeks;save();render();};});}
function startScreen(){
if(!WEEKS.includes(state.weeks))state.weeks='1–2';
if(state.weeks!=='1–2'){$('app').innerHTML=weekPicker()+`<section class="week-empty" aria-live="polite"><span class="eyebrow">LING313</span><h1>${state.weeks==='12'?'Week':'Weeks'} ${state.weeks}</h1><p>To be added</p></section>`;bindWeekPicker();return;}
$('app').innerHTML=weekPicker()+`<section class="intro"><div><span class="eyebrow">LING313 · WEEKS 1–2</span><h1>Phonology<br><span class="accent">Practice</span></h1><p class="muted">Work through 16 problems in four rounds. Describe sounds, evaluate evidence, and test phonological analyses of Turkish.</p><div class="chips"><span class="chip">30–35 minutes</span><span class="chip">16 problems</span><span class="chip">W1 + W2</span></div><p style="font-size:14px" class="muted">Discuss each problem before submitting an answer and its justification.</p></div><section class="setup" aria-label="Session setup"><span class="eyebrow">SESSION SETUP</span><h2>Choose a format</h2><div class="mode-buttons"><button id="teamMode" class="${state.mode==='team'?'selected':''}" aria-pressed="${state.mode==='team'}">Team mode<small>One team · one device</small></button><button id="classMode" class="${state.mode==='class'?'selected':''}" aria-pressed="${state.mode==='class'}">Projector mode<small>Whole-class discussion</small></button></div><label for="teamName">${state.mode==='class'?'Class name':'Team name'} <span class="muted">(optional)</span></label><input id="teamName" maxlength="35" placeholder="e.g. Group 1" value="${esc(state.team)}" autocomplete="off"><button class="primary" id="startBtn">${state.answers.length?'Resume session':'Start practice'}</button><p class="muted" style="font-size:13px;margin:15px 0 0">Each problem: 60 points for the answer, 40 for the justification.</p>${!storageOK?'<p class="storage-warning">Browser storage is unavailable. Keep this page open to retain your progress.</p>':''}</section></section><section class="rooms" aria-label="Four rounds">${ROOMS.map((r,i)=>`<div class="room-card"><span class="room-number">0${i+1}</span><h3>${r.name}</h3><p>${r.intro}</p></div>`).join('')}</section>`;
bindWeekPicker();
$('teamMode').onclick=()=>{state.team=$('teamName').value;state.mode='team';save();render();};$('classMode').onclick=()=>{state.team=$('teamName').value;state.mode='class';save();render();};$('startBtn').onclick=()=>{state.team=$('teamName').value.trim();state.big=state.mode==='class';state.screen=state.answers.length===16?'results':'play';resetDraft();save();render();focusMain();};}
function optionHTML(options,selected,group,locked){return `<div class="options">${options.map((o,i)=>`<button class="option ${selected.includes(i)?'selected':''}" data-${group}="${i}" aria-pressed="${selected.includes(i)}" ${locked?'disabled':''}><span class="key">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`).join('')}</div>`;}
function playScreen(){const c=CASES[state.index];if(!c){$('app').innerHTML='<p>The problem could not be loaded. Please reload the page.</p>';return;}const room=Math.floor(state.index/4),n=state.index%4,locked=state.answers[state.index],d=locked||draft;
$('app').innerHTML=`<div class="topline"><span class="eyebrow">${esc(state.team||(state.mode==='class'?'CLASS':'TEAM'))} · PROBLEM ${state.index+1} / 16</span><div class="score">${score()} <small>/ 1600</small></div></div><nav class="progress" aria-label="Round progress">${ROOMS.map((r,i)=>`<div class="${i===room?'active':i<room?'done':''}">0${i+1} · ${r.short}${i<room?' ✓':''}</div>`).join('')}</nav><div class="play-grid"><section class="case"><span class="eyebrow">ROUND 0${room+1} · ${ROOMS[room].name}</span><h2>${c.title}</h2><div class="data">${esc(c.data)}</div><p class="question">${esc(c.q)}</p>${c.type==='fields'?`<div class="fields">${c.fields.map((f,i)=>`<div class="field-row"><label for="field${i}">${esc(f[0])}</label><select id="field${i}" data-field="${i}" ${locked?'disabled':''}><option value="">Select…</option>${f[1].map((v,k)=>`<option value="${k}" ${d.fields[i]===k?'selected':''}>${esc(v)}</option>`).join('')}</select></div>`).join('')}</div>`:optionHTML(c.options,d.answer,'answer',locked)}<section class="reason"><h3>Choose a justification</h3>${optionHTML(c.reasons,[d.reason],'reason',locked)}</section>${d.hint?`<aside class="hint"><strong>Hint · −20 points</strong><br>${esc(c.hint)}</aside>`:''}<div class="case-actions">${!locked?`<button class="quiet" id="hintBtn" ${d.hint?'disabled':''}>Show hint (−20)</button><button class="primary" id="submitBtn">Submit answer</button>`:`<span class="muted">Your first response has been recorded.</span><button class="primary" id="nextBtn">${n===3?'Finish round':'Next problem'}</button>`}</div><p id="validation" class="storage-warning" role="status"></p>${locked?feedback(c,locked):''}</section><aside class="sidebar"><span class="eyebrow">ROUND FOCUS</span><h3>${ROOMS[room].intro}</h3><div class="dots">${[0,1,2,3].map(i=>`<span class="${i<n?'done':i===n?'current':''}">${i<n?'✓':i+1}</span>`).join('')}</div><p>Answer: 60 points<br>Justification: 40 points<br>Hint: −20 points</p><div class="side-block"><h3>${state.mode==='class'?'Discuss before submitting':'Assign roles'}</h3><p>${state.mode==='class'?'Collect each team’s answer and justification before submitting the class response.':'One person reads the data, another checks the analysis, and another explains the reasoning.'}</p></div><div class="side-block"><p>ʰ = aspiration<br>[ ] = phonetic transcription<br>/ / = phonemic notation<br>$ = syllable boundary · # = word boundary</p></div></aside></div>`;
if(!locked){document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.answer);draft.answer=c.type==='multi'?(draft.answer.includes(i)?draft.answer.filter(x=>x!==i):[...draft.answer,i]):[i];render();document.querySelector(`[data-answer="${i}"]`)?.focus({preventScroll:true});});document.querySelectorAll('[data-reason]').forEach(b=>b.onclick=()=>{draft.reason=Number(b.dataset.reason);render();document.querySelector(`[data-reason="${draft.reason}"]`)?.focus({preventScroll:true});});document.querySelectorAll('[data-field]').forEach(s=>s.onchange=()=>{draft.fields[Number(s.dataset.field)]=s.value===''?null:Number(s.value);});$('hintBtn').onclick=()=>{draft.hint=true;render();};$('submitBtn').onclick=submit;}else $('nextBtn').onclick=next;
}
function grade(c,d){let fraction;if(c.type==='fields')fraction=c.fields.reduce((n,f,i)=>n+(d.fields[i]===f[2]?1:0),0)/c.fields.length;else if(c.type==='multi')fraction=d.answer.length===c.answer.length&&c.answer.every(v=>d.answer.includes(v))?1:0;else fraction=d.answer[0]===c.answer?1:0;return {solution:Math.round(60*fraction),reasonPoints:d.reason===c.r?40:0,points:Math.max(0,Math.round(60*fraction)+(d.reason===c.r?40:0)-(d.hint?20:0))};}
function submit(){const c=CASES[state.index];if(state.answers[state.index])return;if(draft.reason===null||(c.type==='fields'?c.fields.some((_,i)=>!Number.isInteger(draft.fields[i])):!draft.answer.length)){$('validation').textContent='Complete the answer and select a justification before submitting.';return;}state.answers.push({...draft,...grade(c,draft)});save();render();$('app').querySelector('.feedback').scrollIntoView({behavior:'smooth',block:'nearest'});}
function answerText(c){return c.type==='fields'?c.fields.map(f=>f[0]+': '+f[1][f[2]]).join(' · '):c.type==='multi'?c.answer.map(i=>c.options[i]).join(' + '):c.options[c.answer];}
function feedback(c,a){return `<section class="feedback" aria-live="polite"><h3>${a.solution===60&&a.reasonPoints===40?'Correct answer and justification.':a.solution===60?'Correct answer; review the justification.':'Review the analysis below.'} <span class="accent">+${a.points}</span></h3><p class="correct-answer"><strong>Answer:</strong> ${esc(answerText(c))}</p><p><strong>Justification:</strong> ${esc(c.reasons[c.r])}</p><p>${esc(c.explain)}</p><p class="source">Answer ${a.solution}/60 · Justification ${a.reasonPoints}/40${a.hint?' · Hint −20':''}<br>Reference: ${esc(c.source)}</p><p><strong>Discussion:</strong> ${esc(c.talk)}</p></section>`;}
function next(){if(state.index%4===3){state.screen='break';}else{state.index++;resetDraft();}save();render();focusMain();}
function breakScreen(){const i=Math.floor(state.index/4);$('app').innerHTML=`<section class="break-panel"><span class="eyebrow">ROUND 0${i+1} COMPLETE</span><div class="seal" aria-hidden="true">${ROOMS[i].symbol}</div><h1>${i===3?'All rounds complete.':'Round complete.'}</h1><p>${ROOMS[i].name}: <strong class="accent">${roomScore(i)} / 400</strong></p><p class="muted">${ROOMS[i].debrief}</p><p style="font-size:15px" class="muted">${i<3?'Discuss for one minute, then rotate roles within your team.':'Review how the evidence supports the final analysis.'}</p><button class="primary" id="continueBtn">${i<3?'Start next round':'View results'}</button></section>`;$('continueBtn').onclick=()=>{if(i===3)state.screen='results';else{state.index++;state.screen='play';resetDraft();}save();render();focusMain();};}
function resultsScreen(){$('app').innerHTML=`<section class="results"><span class="eyebrow">SESSION COMPLETE · ${esc(state.team||'TEAM')}</span><h1>Session results</h1><p class="muted">Use the problem review below to revisit your answers and reasoning.</p><div class="result-score">${score()} <small>/ 1600</small></div><div class="result-grid">${ROOMS.map((r,i)=>`<div><span>${r.name}</span><strong>${roomScore(i)} <small>/ 400</small></strong></div>`).join('')}</div><p><strong>Final analysis:</strong> In the W2 analysis, [c] near front vowels can be a predictable realization of /k/. The kar–kâr contrast provides evidence for distinct /k/ and /c/ before a back vowel.</p><details><summary>Optional discussion: novel words and morphology · unscored</summary><p><strong>sof = 2, mürü = 3.</strong> Using the invented words from W1, complete the sentence: “Merdivenleri sof-___ sof-___ çıkmak kolay, mürü-___ mürü-___ çık da göreyim.”</p><p>What does your ability to add suffixes to novel words suggest about linguistic knowledge? Identify the root, suffix, and suffix form.</p><details><summary>Suggested analysis</summary><p><strong>sofar sofar · mürüşer mürüşer.</strong> These are the expected forms with the distributive suffix -(ş)Ar: sof + ar, mürü + şer. Extending the pattern to novel roots illustrates productive knowledge. The suffix’s detailed analysis can be discussed later.</p></details></details><h2>Problem review</h2><p class="muted">Revisit any errors and explain how you would revise the analysis.</p>${CASES.map((c,i)=>`<details><summary>${String(i+1).padStart(2,'0')} · ${esc(c.title)} <span class="muted">— ${state.answers[i]?.points??0}/100</span></summary><p class="correct-answer">${esc(answerText(c))}</p><p>${esc(c.explain)}</p><p><strong>Discussion:</strong> ${esc(c.talk)}</p><p class="source">${esc(c.source)}</p></details>`).join('')}<div class="wide-actions"><button class="primary" id="copyResult">Copy results</button><button id="restart">Start again</button></div><p id="copyStatus" role="status"></p><p class="footer-note">LING313 · W1 handout-a / W1 handout-b / W2 presentation-a<br>Original practice questions based on the supplied course materials.</p></section>`;$('copyResult').onclick=async()=>{const report=`LING313 Phonology Practice — ${state.team||'Team'}: ${score()}/1600\n`+ROOMS.map((r,i)=>`${r.name}: ${roomScore(i)}/400`).join('\n');try{await navigator.clipboard.writeText(report);$('copyStatus').textContent='Results copied. You can share them with the class.';}catch(e){$('copyStatus').textContent=report;}};$('restart').onclick=()=>{$('guide').showModal();$('resetConfirm').hidden=false;};}
$('guideBtn').onclick=()=>$('guide').showModal();$('closeGuide').onclick=()=>$('guide').close();$('displayBtn').onclick=()=>{state.big=!state.big;save();render();};$('brand').onclick=e=>{e.preventDefault();state.screen='start';save();render();};$('resetBtn').onclick=()=>{$('resetConfirm').hidden=false;};$('cancelReset').onclick=()=>{$('resetConfirm').hidden=true;};$('confirmReset').onclick=()=>{state={weeks:state.weeks,screen:'start',mode:state.mode,team:state.team,index:0,answers:[],big:false};resetDraft();save();$('resetConfirm').hidden=true;$('guide').close();render();focusMain();};
resetDraft();render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_current_case',description:'Read the current visible case and game progress; does not submit an answer.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({screen:state.screen,caseNumber:state.index+1,total:16,score:score(),title:state.screen==='play'?CASES[state.index]?.title:null})})).catch(()=>{});}catch(e){}}
